### PR TITLE
fix(build): update max build version to survive in EAPs

### PR DESCRIPTION
**Pull request by cosmtrek**

### CODE REVIEW

**Comment by amtmolecule** [comment]
@zxqfl can this please be merged? TabNine is unusable in the latest EAP version of Webstorm.

**Comment by qq286735628** [comment]
@zxqfl can this please be merged？tabNine is incompatible with WebStorm 2019.3 ，issue is #10

**Comment by Flixt** [comment]
Until this is merged you can use (manually import):

[TabNine-0.1.3.jar.zip](https://github.com/zxqfl/tabnine-intellij/files/3921646/TabNine-0.1.3.jar.zip)

**Comment by Danmou** [comment]
This is fixed in the latest release, but you might need to go to the plugin settings in PyCharm to update (at least for me it didn't happen automatically).

**Pull request closed without merging**
