### PR TITLE
DEV2-3164 improve plugin updates lifecycle

### PR DESCRIPTION
**Pull request by yonip23**
### Changes
1. introduce `"Automatically install plugin updates when available"` checkbox in the settings panel - set to true by default
2. run an update task every 24 hours, and upon IDE restart
    1. if an update is available:
        1. if the user enabled auto updates - install the update and show a notification that requires a restart
        2. else - show a notification that an update is available, with an option to open the `Settings -> Plugins` panel
3. introduce a "restart" dialog if the user updated the settings that require a restart in the settings panel

See the videos attached below:

### Show manual update notification
https://github.com/codota/tabnine-intellij/assets/67855609/0682bd4d-c846-415b-ba0c-d5849777ebe0

### Install plugin update automatically
https://github.com/codota/tabnine-intellij/assets/67855609/a3c81b9e-2c0b-4ef8-9991-2d18e04c6b39

### Restart after settings change
https://github.com/codota/tabnine-intellij/assets/67855609/5d4cc5f9-6f8f-4dd6-96b6-e501d89763c9

### CODE REVIEW

**Comment by yairco1990** [comment]
Very nice!! love it ❤️

**Review by amircodota — APPROVED** [review]
Looks great.

Checking every 24 hours is too slow imo. I would change it to once every 1-4 hours, something around there.

Also - please make sure to test on the earliest and latest versions we support if you did not do so yet.

Great Job :+1:

**Comment by yonip23** [comment]
@amircodota 
> Checking every 24 hours is too slow imo

I thought so as well, I wasn't sure. 4h sounds legit IMO, I don't want it to be too חופר either

**Review by dimacodota — APPROVED** [review]
lgtm, great job! well done

**Pull request merged**
