### PR TITLE
DEV2-1383 add auto import toggle

### PR DESCRIPTION
**Pull request by yonip23**

### CODE REVIEW

**Review by yairco1990 — APPROVED** [review]
lgtm
are we sure we want to change the default behavior?

**Comment by yonip23** [comment]
That's what I'm trying to do lol
Will make sure it's true by default of course

**Comment by yonip23** [comment]
@yairco1990 @dimacodota I removed the xml settings file from my machine, restarted the IDE and made sure that the settings panel opens with this checkbox selected, and that the auto import actually works.
This is the new text:
image

**Review by dimacodota — APPROVED** [review]
lgtm

**Pull request merged**
