### PR TITLE
DEV2-2191 don't throw exception on index out of bounds

### PR DESCRIPTION
**Pull request by yonip23**

### CODE REVIEW

**Comment by yairco1990** [comment]
can't we only check when we get the event if the offset is out of the document range and if so, ignore it?

**Comment by yonip23** [comment]
> can't we only check when we get the event if the offset is out of the document range and if so, ignore it?

this will yield the same result as this pr, right? if you're in an invalid position you won't get completions.

i prefer to wrap it all with try-catch because all the other 3 lines in these functions are dangerous as well, so instead of understanding each edge case and writing 3 `if`s in both functions, I think its more robust to just catch any exception because all the handling is the same - just skip this completion.
wdyt?

**Review by dimacodota — APPROVED** [review]
lgtm

**Review by yairco1990 — APPROVED** [review]
lgtm

**Pull request merged**
